### ISSUE TITLE
Lint errored by using artifact attestations

### ISSUE THREAD

**Issue by siad007** [reviewdog/action-actionlint#125]
When using artifact attestations described in https://docs.github.com/en/actions/security-guides/using-artifact-attestations-to-establish-provenance-for-builds the actionlint errors with an unknown permission:

**Output**
```
unknown permission scope "attestations". all available permission scopes are "actions", "checks", "contents", "deployments", "discussions", "id-token", "issues", "packages", "pages", "pull-requests", "repository-projects", "security-events", "statuses"
```

**Example workflow**
```
name: build-attest

on:
  workflow_dispatch:

jobs:
  build:
    permissions:
      id-token: write
      contents: read
      attestations: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build artifact
        run: make my-app
      - name: Attest
        uses: actions/attest-build-provenance@v1
        with:
          subject-path: '${{ github.workspace }}/my-app'
```
