### ISSUE TITLE
shellcheck directive not taken into account

### ISSUE THREAD

**Issue by NickDub** [reviewdog/action-actionlint#129]
Here is some of the code from my Github workflow: 
```yaml
- name: Apply Env Provisioning
  run: |
    # shellcheck disable=SC2086
    envsubst < ${{ inputs.provisioning-file-path }} > provisioning-replaced.yaml
```
and actionlint return this error:
`shellcheck reported issue in this script: SC2086:info:4:29: Double quote to prevent globbing and word splitting [shellcheck]`

The [shellcheck directive](https://github.com/koalaman/shellcheck/wiki/Ignore) to disable the instance is not taken into account.
