### ISSUE TITLE
Flags not properly passed in entrypoint

### ISSUE THREAD

**Issue by JennyFigueroaMSR** [reviewdog/action-actionlint#142]
The reviewdog flags (and possibly the actionlint flags) are not being properly passed to their commands. The ${INPUT_XXX_FLAGS} need to be wrapped in quotes.

For example, this does not work:
```yaml
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Call Actionlint
        id: action
        uses: reviewdog/action-actionlint@v1.56.0
        with:
          reporter: local
          reviewdog_flags: -diff="git diff main"
```

It fails with:
```
reviewdog: invalid command line string
```

I tested this by using `act` in offline mode to run a modified image of the Dockerfile. It happened to get stuck when running it, so I shelled into the container. When shelled into the container:
* I ran the entrypoint with `sh /entrypoint.sh` and verified that the error still occurs
* I added quotes around ${INPUT_REVIEWDOG_FLAGS} in the entrypoint
* I ran the entrypoint again and saw the results I was expecting

I suspect that this may have something to do with https://github.com/reviewdog/action-actionlint/issues/80 as well.

edit: Looks like adding quotes doesn't fix it as I thought it would. Needs some more tinkering for a real solution
