### ISSUE TITLE
not defined in object type error on marketplace action dorny/paths-filter@v2

### ISSUE THREAD

**Issue by frank-long** [reviewdog/action-actionlint#37]
```
 - name: Checkout repo
        uses: actions/checkout@v2
      - id: filterchanges
        uses: dorny/paths-filter@v2
        with:
          filters: 'files: .github/workflows/*.yml'
      - name: lint
        if: ${{ steps.filterchanges.outputs.files == 'true'}}
```

[actionlint] reported by reviewdog 🐶 property "files" is not defined in object type {changes: any} [expression]

I don't get this error with the cmd line version, workflow runs fine
Can't see what's wrong with it. I'm using  dorny/paths-filter@v2
