### ISSUE TITLE
PR comment reviews not working

### ISSUE THREAD

**Issue by sammcj** [reviewdog/action-actionlint#75]
I've been trying to get PR comment reviews to work but can't get the action to create the comment, there's no error messages from the job etc... which is odd.

Just wondering if this is a known bug or if I've misunderstood the readme instructions?

```yaml
name: "Lint"
on:
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize

jobs:
  actionlint:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v3
      - uses: reviewdog/action-actionlint@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          reporter: github-pr-review
```
