### ISSUE TITLE
issues using `actionlint_flags` with the `-ignore` flag?

### ISSUE THREAD

**Issue by pcassaretto-cmc** [reviewdog/action-actionlint#80]
With the following 

```
  with:
    actionlint_flags: -ignore 'a pattern' 
```

actionlint seems to run without producing any findings whatsoever but reports no errors.  I noticed in the logs 

```
"/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/repo/repo":"/github/workspace" ghcr.io/reviewdog/action-actionlint:v1.28.0
could not read "pattern'": open pattern': no such file or directory
2022/08/26 15:13:25 [actionlint] reported: https://github.com/org/repo/runs/_id_ (conclusion=success)
```

so it appears to try and open a file with the name of the last word in the pattern to be ignored.  I have tried different approaches surrounding the flag value in different quotes to no avail?

What am I doing wrong?

**Comment by shogo82148** [comment]
Can we have whole contents of your `.github/workflow/*.yaml`?

**Comment by shichanson** [comment]
I also encountered this problem. Don't know how to solve this problem.
```yaml
name: "test"

on:
  pull_request:
    branches:
      - master
    paths:
      - ".github/workflows/**"

jobs:
  actionlint:
    runs-on: ["self-hosted"]
    steps:
      - uses: actions/checkout@v3
      - uses: reviewdog/action-actionlint@v1
        with:
          actionlint_flags: -ignore 'label ".+" is unknown' -ignore '".+" is potentially untrusted'
          reporter: github-pr-review
```

**Comment by shichanson** [comment]
@pcassaretto-cmc Don't say how I use it, there is no doubt that you are a bug. My usage scenario is that I don't want to check my runner label because I have a lot of runners. My github is deployed privately.

**Comment by sammcj** [comment]
My workaround for this problem is to generate a config file on the fly before the check is run:

```yaml
      - uses: actions/checkout@v3
      - name: build actionlint config for runner labels
        shell: bash
        run: |
          cat > .github/actionlint.yaml<< EOF
          self-hosted-runner:
            # Labels of self-hosted runner in array of string
            labels:
              - aws-redacted-1233456790
              - aws-redacted-1233456790
              - aws-redacted-1233456790
              - aws-redacted-1233456790
              - aws-redacted-1233456790
              - aws-redacted-1233456790
              - aws-redacted-1233456790
              - aws-redacted-1233456790
              - aws-redacted-1233456790
              - aws-redacted-1233456790
              - aws-redacted-1233456790
              - aws-redacted-1233456790
          EOF
      - uses: reviewdog/action-actionlint@v1
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SHELLCHECK_OPTS="-e SC2086 -e SC2129 -e SC1091 -e SC2050 -e SC2194 -e SC2154 -e SC2157"
        with:
          actionlint_flags: -config-file '.github/actionlint.yaml'
          fail_on_error: true
          level: error
          reporter: github-pr-review
          filter_mode: file
```
